id: PF8091AAA
initial_creation_type: input
source_metadata:
  title: Dzogchen Series
  language: fr
  description: 'The following texts are available as part of our Dzogchen (rdzogs
    chen) or Great Perfection series:'
  volume:
    f2d578f14ae54f27bde0d7631ff01788:
      title: Advice for Hor Özer
      parent: Advice
    e59a76caeca34ffc8886cf2507a31541:
      title: Advice for Palseng
      parent: Advice
    f2102ba17b7e43ca9a27664416375b1c:
      title: Memorandum on the Subject of Mahāmudrā and Dzogchen Instructions
      parent: Advice
    3351c5cab7d14575864c2c039597c289:
      title: Advice for Garje Khamtrul Rinpoche
      parent: Advice
    8cf26fb3ad2e4794afc144a419d88bc8:
      title: Advice on Recognizing the Nature of Mind
      parent: Advice
    8c4abda76d204e4db07e9b013a3eb012:
      title: 'Advice: Emptying the Three Realms of Existence'
      parent: Advice
    0a7b68606c0043a2bcf32cc70bfda720:
      title: An Instruction on the Great Perfection
      parent: Advice
    48b93c4de77147d8966db286dccfce9d:
      title: Brief Dzogchen Instruction
      parent: Advice
    1f98515225554f00bc7c1b32f81e3a01:
      title: Direct Instruction
      parent: Advice
    1e0869f7d0c7412da8ccf3f1e4eeddfe:
      title: Summary of the Key Points of Advice on Trekchö
      parent: Advice
    374f46e46d5d439a92934debf71b16a4:
      title: Vajra Verses on the Natural State
      parent: Advice
    91d3d3770959487d852340e9599fda2b:
      title: Advice for a King
      parent: Advice
    9310014df45a4a9f833bef427532a6a6:
      title: A Song of Advice for Gok Zangden
      parent: Advice
    a6f52d1f52d0494aac6c3a0b6e8ce475:
      title: A Song to Introduce the Unmistaken View of the Great Perfection
      parent: Advice
    b7198adbb2ea4e0b9c60511c0ac5edc2:
      title: 'Naturally Liberating Whatever You Meet: A Concise Instruction for Realizing
        the Nature of Mind'
      parent: Advice
    2559a4d7290f4a6981675954a00a07b5:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Advice
    dfd3fa0c5ad44ed5953d588cd01b14c7:
      title: 'Vomiting Gold: A Pith Instruction in the Form of Advice for the Diligent
        Practitioner, the Excellent Atsang'
      parent: Advice
    aac3e3a5b37644e0b1ff7580a4090d2e:
      title: A Liberating Reminder
      parent: Advice
    3ac1a35bf85f44fd9884343e39beb4e1:
      title: 'A Mirror Revealing the Crucial Points: Advice on the Ultimate Meaning'
      parent: Advice
    decfd723cfc945298d860c2084aedb14:
      title: 'A Wish-Fulfilling Gem: Guidance on the Meaning of Being at Ease with
        Illusion, A Dzogchen Teaching'
      parent: Advice
    de453fd8630c4ce18c2b2bc0bdd3229e:
      title: 'From ''Finding Comfort and Ease in Meditation'': A Guide to Locations
        for Cultivating Samadhi'
      parent: Advice
    c551413d3a594722bee0e8c65dc857a7:
      title: 'From ''Finding Comfort and Ease in Meditation'': The Practitioner of
        Meditation'
      parent: Advice
    eb86f3860b784cae9404336b085bb5a4:
      title: 'A Lamp to Dispel Darkness: An Instruction that Points Directly to the
        Very Essence of Mind in the Tradition of ‘the Old Realized Ones’'
      parent: Advice
    bd6e4ffa49c94249908cfceb2ef2444f:
      title: Pith Instruction on the Three Crucial Statements
      parent: Advice
    0b7e16ca076440d39a046dd119f6a749:
      title: The Essence of Mind
      parent: Advice
    e3094ccd921b4f33b9820ffe0e384b07:
      title: 'The Essence of Wisdom: How to Sustain the Face of Rigpa'
      parent: Advice
    2170d6e692d142cabf644b19e41647b3:
      title: The Key Points of Trekchö
      parent: Advice
    00e3852a0d44467eb87f2b6860212ded:
      title: The Nature of Mind
      parent: Advice
    042d8ab8c1774096a0a7e6632a47e819:
      title: Advice on the View, Meditation, Action and Fruition
      parent: Advice
    32a4945290044f3cbb189e5c5e54be05:
      title: The Pointing-the-Staff Instruction
      parent: Advice
    d5354ae5dad44e4589abbd6049c08626:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Advice
    0886174beae4429094b1f765a3485955:
      title: Principles of the Dzogchen Practice of Khordé Rushen
      parent: Advice
    00eec7af35c847d082a9e167a1224232:
      title: The Five Wisdoms
      parent: Advice
    d9a2370210b1456584763c65cf413b15:
      title: Advice on How to Put the Meaning of the Natural Great Perfection into
        Practice
      parent: Advice
    01ee14bc4a634c01bfb23272941e2d2b:
      title: 'Self-Liberating Meditation: A Profound Method for Attaining Enlightenment
        according to the Ultimate Great Perfection'
      parent: Advice
    d5f2b01fdf874b75877dc6f9a665cb4c:
      title: Advice from the Lips of Tertön Sogyal
      parent: Advice
    d87cc03379b94c6680c0f28789175447:
      title: A Torch to Illuminate Crucial Points of the Path of Meditation
      parent: Advice
    98f7c45f28174d989749aa5561afeaeb:
      title: The Four Uncommon Samayas of the Great Perfection
      parent: Advice
    6710a5cca3404aca85b16314a45fb684:
      title: A Brief Presentation of View, Meditation and Action
      parent: Advice
    de683d7acc1b4844ba9778009dcbf061:
      title: From the Oral Tradition of the Lama of Nyarong
      parent: Advice
    41eeddab9205418d8045ccc72b15afa8:
      title: On the Final Words of Orgyen Tendzin Norbu
      parent: Commentaries
    9f3a20e419934785a344abcf47cba4b1:
      title: 'The Precious Jewelled Key: A Synopsis of the Aspiration of the Great
        Perfection Mañjuśrī'
      parent: Commentaries
    e46adec708dc4d178e5bbd3a57ebf6cd:
      title: 'The Prayer of the Ground, Path & Fruition from the Heart-Essence of
        the Vast Expanse:'
      parent: Commentaries
    0a9c950989224303877dd3d39de98a93:
      title: Commentary on Vajra Verses on the Natural State
      parent: Commentaries
    670e39a512c442f385eb3ebbd1365c35:
      title: Prayer to the Gurus of the Dzogchen Lineage
      parent: Lineage Prayers
    5447bb73ba494ce5acf9ec69c93e78ee:
      title: A Prayer to Shower Down the Rain of Wisdom
      parent: Lineage Prayers
    b45d28d7cc364f7cbfca70e05b3dfb46:
      title: How to Count the Four Permutations of Actual and Basis
      parent: Notes
    84d2fdd267e54ee5a82c739070469984:
      title: Commentary on Some Terms from the Great Perfection
      parent: Notes
    f3691e2f7338480bbc147da33d9cfda2:
      title: Brief Explanation of Clarification and Transcendental Resolution from
        the Oral Tradition of Nyala Sogyal
      parent: Notes
    cf27b6ce844a46a199905b99a579a610:
      title: How Liberation and Delusion Develop Out of the Clear Light of the Ground,
        etc.
      parent: Notes
    eac9e84b56ee4b8c9057f129e7ed1377:
      title: Notes from the Oral Tradition on Ālaya, Ālaya Consciousness, etc.
      parent: Notes
    a2e6f717890d4c68b73b881978dfa1f4:
      title: Dzogchen Aspiration Prayer
      parent: Prayers
    bedbd62947f0457e810c017775f1057e:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Prayers
    7b2b4acdcd784dc78df37ac8e4a3b140:
      title: A Dzogchen Tögal Prayer
      parent: Prayers
    a4dd4315ded54757a166fdbf7be8f58d:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Prayers
    c813f7ffcf9c4d8baaf6e225b6ff8b0b:
      title: 'The Pure Three Kāyas Ablaze in Perfect Splendour: A Prayer Based on
        the Meaning of the Great Perfection'
      parent: Prayers
    114b65b5d9e640d18d4bc3e26736a8ff:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      parent: Prayers
    2142202af8f74994ac0da8a89ef75efd:
      title: Prayer to Nyala Pema Dündul
      parent: Prayers
    c1dc62c5449b477e8393eb8e7a10e2d6:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Prayers
    be5ab290f6ec4e6dbd1dc2f81043afca:
      title: The Song of the Vajra
      parent: Songs
    e59691a534da41869219b293e07e93d9:
      title: A Song in Six Verses
      parent: Songs
    ca4032da23074bee9f89baa73938865e:
      title: Song of Experiential Certainty
      parent: Songs
    3e16ebb9531542be8986a344ca4e7a79:
      title: Spontaneously Written Song of Experience
      parent: Songs
    47cfc80985874973877712a909aaddfb:
      title: In This Pure Awareness
      parent: Songs
    6f12cd206df345d798de66dd7bdfb018:
      title: 'Aho Ye: Impressions of an Insightful Experience'
      parent: Songs
    353a70cc8cc1410986202cbc8765ddb7:
      title: Five-Verse Doha of Yogic Realization
      parent: Songs
    f079869fab9f44758b9031dfbe209d54:
      title: The Final Testament of Yukhok Chatralwa as Transmitted to Lama Rigdzin
        Nyima
      parent: Testament
created_at: '2022-03-01T03:36:31.994503'
last_modified_at: '2022-03-01T03:36:31.994506'
